server:
  port: 8080

topic:
  name: frames

cron:
  rate: 5000
well:
  number: 3
frame:
  voltage:
    min-value: 200
    max-value: 240
  current:
    min-value: 40
    max-value: 60
  speed:
    min-value: 2600
    max-value: 3300
  frequency:
    min-value: 40
    max-value: 60
  temperature:
    min-value: 175
    max-value: 225
  pressure:
    min-value: 1200
    max-value: 2500
  liquid-flow-rate:
    min-value: 5
    max-value: 15
