server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    topic:
      oil-station-topic: oil_station_frames

station:
  well:
    number: 3
  cron:
    rate: 7000
