server:
  port: 8080

topic:
  name: frames

cron:
  rate: 5000

well:
  number: 3

frame:
  voltage:
    min-value: 200
    max-value: 240
    min-critical-value: 201.961
    max-critical-value: 239.726
  current:
    min-value: 40
    max-value: 60
    min-critical-value: 40.853
    max-critical-value: 59.906
  speed:
    min-value: 2600
    max-value: 3300
    min-critical-value: 2608.534
    max-critical-value: 3297.802
  frequency:
    min-value: 40
    max-value: 60
    min-critical-value: 40.969
    max-critical-value: 59.786
  temperature:
    min-value: 175
    max-value: 225
    min-critical-value: 175.617
    max-critical-value: 224.131
  pressure:
    min-value: 1200
    max-value: 2500
    min-critical-value: 1202.411
    max-critical-value: 2488.356
  liquid-flow-rate:
    min-value: 5
    max-value: 15
    min-critical-value: 5.092
    max-critical-value: 14.89
